title: MI2 Center
email: your-email@example.com
description: >-
  Manifold-Constrained Research. U.S. Pat. Pend. 63/902,243.
url: "https://pgjkmqpw52-hue.github.io"
baseurl: ""
github_username: pgjkmqpw52-hue
repository_name: pgjkmqpw52-hue.github.io
theme: al-folio
plugins:
  - jekyll-feed
  - jekyll-sitemap
